spring.application.name=CART-SERVICE

spring.config.import=configserver:http://localhost:8888

spring.datasource.url = jdbc:postgresql://localhost:5432/EMPLOYEE
spring.datasource.username = postgres
spring.datasource.password = kartikey
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port=9093


Resilience4j.circuitbreaker.instances.Cartservice.registerHealthIndicator=true
Resilience4j.circuitbreaker.instances.Cartservice.slidingWindowSize: 5
Resilience4j.circuitbreaker.instances.Cartservice.minimumNumberOfCalls: 5
Resilience4j.circuitbreaker.instances.Cartservice.failureRateThreshold: 50
Resilience4j.circuitbreaker.instances.Cartservice.waitDurationInOpenState: 10s
Resilience4j.circuitbreaker.instances.Cartservice.permittedNumberOfCallsInHalfOpenState: 3
Resilience4j.circuitbreaker.instances.Cartservice.eventConsumerBufferSize: 10
resilience4j.circuitbreaker.instances. sampleService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances. sampleService.sliding-window-type=COUNT_BASED

Management.endpoints.web.exposure.include=*

